<a href="https://colab.research.google.com/github/hsallrounder/Application-Of-Machine-Learning-In-Industries-Workshop-2023/blob/main/Torch_Tensor_Application_Of_Machine_Learning_In_Industries_Workshop_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
torch.__version__

'1.13.1+cu116'

In [ ]:
import numpy as np

In [ ]:
lst=[3,4,5,6]
arr=np.array(lst)

In [ ]:
tensors=torch.from_numpy(arr)
print(tensors)
print(type(tensors))

tensor([3, 4, 5, 6])
<class 'torch.Tensor'>


In [ ]:
tensors[1:4]

tensor([4, 5, 6])

In [ ]:
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)